name: web
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - click=7.1.2
  - flask=1.1.2
  - flask-sqlalchemy=2.4.4
  - itsdangerous=1.1.0
  - jinja2=2.11.2
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libgomp=9.3.0
  - liblapack=3.9.0
  - libopenblas=0.3.12
  - libstdcxx-ng=9.3.0
  - markupsafe=1.1.1
  - ncurses=6.2
  - numpy=1.20.0
  - openssl=1.1.1i
  - pandas=1.2.1
  - pip=20.3.3
  - python=3.7.3
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2021.1
  - readline=8.0
  - setuptools=49.6.0
  - six=1.15.0
  - sqlalchemy=1.3.22
  - sqlite=3.34.0
  - tk=8.6.10
  - tqdm=4.56.0
  - werkzeug=1.0.1
  - wheel=0.36.2
  - xz=5.2.5
  - yapf=0.30.0
  - zlib=1.2.11
  - pip:
    - aniso8601==7.0.0
    - flask-graphql==2.0.1
    - flask-graphql-auth==1.3.2
    - graphene==2.1.8
    - graphql-core==2.3.2
    - graphql-relay==2.0.1
    - graphql-server-core==1.2.0
    - mypy==0.790
    - mypy-extensions==0.4.3
    - promise==2.3
    - pyjwt==2.0.0
    - rx==1.6.1
    - typed-ast==1.4.1
    - typing-extensions==3.7.4.3