# This file is genereted by `conda env export --no-builds | grep -v "^prefix: " > environment.yml`
# (the `--no-builds` is important since it unties the environment from the Python version and OS.)
# First edit the `name: web` to a desired name you like. For example `name: deepvocab`
# You should use `conda env create -f environment.yml --name deepvocab` to create new environment
name: web
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bidict=0.21.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.12
  - click=7.1.2
  - colorama=0.4.4
  - cryptography=36.0.0
  - dnspython=2.1.0
  - eventlet=0.33.0
  - flask=1.1.2
  - flask-cors=3.0.10
  - flask-socketio=5.1.1
  - flask-sqlalchemy=2.4.4
  - flask-talisman=0.7.0
  - greenlet=0.4.17
  - gunicorn=20.1.0
  - idna=3.1
  - itsdangerous=1.1.0
  - jinja2=2.11.2
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libgomp=9.3.0
  - liblapack=3.9.0
  - libopenblas=0.3.12
  - libstdcxx-ng=9.3.0
  - markupsafe=1.1.1
  - ncurses=6.2
  - numpy=1.20.0
  - openssl=1.1.1i
  - pandas=1.2.1
  - pip=20.3.3
  - pycparser=2.21
  - pyopenssl=21.0.0
  - pysocks=1.7.1
  - python=3.7.3
  - python-dateutil=2.8.1
  - python-engineio=4.3.0
  - python-socketio=5.5.0
  - python_abi=3.7
  - pytz=2021.1
  - qrcode=7.3.1
  - readline=8.0
  - requests=2.27.1
  - setuptools=49.6.0
  - six=1.15.0
  - sqlalchemy=1.3.22
  - sqlite=3.34.0
  - tk=8.6.10
  - tqdm=4.56.0
  - urllib3=1.26.9
  - werkzeug=1.0.1
  - wheel=0.36.2
  - xz=5.2.5
  - yapf=0.30.0
  - zlib=1.2.11
  - pip:
    - aniso8601==7.0.0
    - flask-graphql==2.0.1
    - flask-graphql-auth==1.3.2
    - graphene==2.1.8
    - graphene-file-upload==1.3.0
    - graphql-core==2.3.2
    - graphql-relay==2.0.1
    - graphql-server-core==1.2.0
    - importlib-metadata==4.8.2
    - jieba==0.42.1
    - markdown==3.3.6
    - mdx-truly-sane-lists==1.2
    - mypy==0.790
    - mypy-extensions==0.4.3
    - promise==2.3
    - pyjwt==2.0.0
    - pymdown-extensions==9.1
    - rx==1.6.1
    - typed-ast==1.4.1
    - typing-extensions==3.7.4.3
    - zipp==3.6.0
