name: web
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - flask=1.1.2
  - flask-sqlalchemy=2.4.4
  - numpy=1.20.0
  - pandas=1.2.1
  - pip=20.3.3
  - python=3.7.3
  - sqlalchemy=1.3.22
  - sqlite=3.34.0
  - tqdm=4.56.0
  - werkzeug=1.0.1
  - pip:
    - flask-graphql==2.0.1
    - flask-graphql-auth==1.3.2
    - graphene==2.1.8
    - graphql-core==2.3.2
    - graphql-relay==2.0.1
    - graphql-server-core==1.2.0